### ISSUE TITLE
API Changes

### ISSUE THREAD

**Issue by matt-chan** [theochem/iodata#1]
Deprecations:
- LockedH5 and the internal H5 file format have been removed.

Parameters:
- The vasp ``dump_poscar`` routine now requires ``data`` to contain an attribute ``cell_frac`` which contains the return value of the cell.to_frac function.

Return values: 
- The ``obasis`` attribute no longer contains an instance of obasis. Rather it contains a dict of all elements necessary to instantiate GOBasis. Simply pass it via GObasis(*obasis.values())
- The ``orb_alpha`` attribute no longer contains an Orbital instance. It has been replaced by four attributes: 
    - ``orb_alpha``: a tuple of (nbasis, nfn). Sufficient to instantiate a Orbital class.
    - ``orb_alpha_coeffs``: formerly Orbitals.coefficients
    - ``orb_alpha_energies``: formerly Orbitals.energies
    - ``orb_alpha_occs``: formerly Orbitals.occs
- The ``cell`` attribute is no longer a Cell instance. Rather it contains a numpy array rvecs which is sufficient to instantiate a Cell instance. 
- The ``grid`` attribute no longer contains an UniformGrid instance. It now contains a dict sufficient to instantiate a UniformGrid instance. It can be used via UniformGrid(*grid.values())
- Vasp IOData instances now require a ``gvecs`` attribute to write the coordinates. 

Non-API breaking changes:
- The molden coefficient normalization now uses internal code to calculate the overlap integrals. The dependency on gbasis has been removed.

**Comment by tovrstra** [comment]
@matt-chan I'll close this one for now because the list is becoming outdated. If you feel we should make a complete list of API changes w.r.t. HORTON2 at some point, just let me know.
