### ISSUE TITLE
Do something about slow test: test_carbon_gs_ae_uncontracted

### ISSUE THREAD

**Issue by tovrstra** [theochem/iodata#108]
This test is slow due to a combination of factors: coverage analysis, lots of computation in one test and slow implementation of the overlap integrals. We should look into options for speeding this one up, because it slows down the typical development cycle a lot.

**Comment by PaulWAyers** [comment]
I think the overlap method in the new gbasis is a lot faster (based on what we've learned so far; it uses recursion instead of the explicit formula), and the screened overlap in the notes I sent should be O(n).

**Comment by tovrstra** [comment]
Good to know. The nice solution then could be a minimal implementation of that scheme in GOBasis. I'd still have to figure out how the coverage analysis slows down the computation, which also makes the tests slower.

**Comment by tovrstra** [comment]
This is no longer the bottleneck, so I'm closing this. (Reviewing takes more time than running tests.)
