### ISSUE TITLE
Make it possible to pass options to load and dump functions

### ISSUE THREAD

**Issue by tovrstra** [theochem/iodata#118]
Adding arbitrary optional arguments tp `load` and `dump` would make it possible to deal with variations of file formats, e.g. extra columns in XYZ files. Another use case can be found in #117 . 

We could add `**kwargs` to the `load_*` and `dump_*` functions and pass them on to corresponding functions in the file format modules. 

@FarnazH Do you know of other relevant use cases?

**Comment by FarnazH** [comment]
@tovrstra This can be also useful if we end up supporting dume_cube of non-scalar properties.

**Comment by tovrstra** [comment]
Is the format of a vector cube defined clearly somewhere? The description on the [cubegen documentation page](https://gaussian.com/cubegen/) leaves some room for interpretation. Here is the relevant part: 

*Densities, the norm of the density gradient, the Laplacian of the density, and the potential are scalars (i.e. one value per point, NVal=1). A gradient cube contains the density plus the vector gradient of the density, so it has four values per point (NVal=4): i.e. the value of the density plus the X, Y, and Z components of its gradient.*

*Cube files have one row per record (i.e., N1\*N2 records each of length N3\*NVal). For formatted output, each row is written out in format (6E13.5). In this case, if N3\*NVal is not a multiple of six, then there may be blank space in some lines.*

Some more details can be found [here](https://h5cube-spec.readthedocs.io/en/latest/cubeformat.html), but I'm not sure if that page counts as authoritative?

**Comment by evohringer** [comment]
@tovrstra This could be also useful to read the element information of different parts of the mol2 file or the pdb file (atom name or last column)
Another interesting case is when you have a certain file format which can come in a different version as the mol2 files.
