### ISSUE TITLE
Spherical contraction ordering documentation

### ISSUE THREAD

**Issue by kimt33** [theochem/iodata#121]
I can't seem to figure out what the spherical contraction ordering is. The docstring in MolecularBasis says "Wikipedia-ordered real solid spherical harmonic", but a quick look at 
https://en.wikipedia.org/wiki/Solid_harmonics and https://en.wikipedia.org/wiki/Spherical_harmonics and https://en.wikipedia.org/wiki/Atomic_orbital makes no mention of dc2, dc1, dc0, -ds1, -ds2, c2, c1, c0, -s1, -s2, s1, or s2. Am I supposed to read this by removing the d, c, and s characters and read the resulting integers as m value?

I remember talking with @tovrstra  about this a while back but I can't seem to remember what these mean. Could the docstrings be updated to either explicitly state their forms or point towards a reference that does it?

**Comment by tovrstra** [comment]
The docstring can indeed be improved. There have been modifications after the original version of the docstring that resulted into something very confusion. I suggest to make the following changes to fix things:

1) Clearly define the meaning of the the strings `dc2` etc. In absence of a minus sign, the first character is for the angular momentum, the second for sine or cosine, the last is for the magnetic quantum number. With these, three pieces, we can refer to the equations given here: https://en.wikipedia.org/wiki/Solid_harmonics#Real_form and ideally also copy over the equations to the docstring. A minus sign can be added as a prefix to indicate a change in sign.

2) The "wikipedia ordering" is the one given here: https://en.wikipedia.org/wiki/Spherical_harmonics#Real_form I believe this is the same as in Helgaker's book? We should add a reference to the docstring to either sources.

3) The minus signs should be removed from the example here: https://github.com/theochem/iodata/blob/master/iodata/basis.py#L160

4) Another example should be added to illustrate the usage of minus signs.

If I overlooked anything, please let me know.

**Comment by kimt33** [comment]
Thank you for your help. I think I have an idea, but I still need some clarifications.

I don't quite know the ordering of the angular momentum after some point. Is it s, p, d, f, g, h, i, j, k, ...? I thought some of the letters were skipped for some reason.

I don't quite get the use of sines and cosines here. Do cosines refer to negative magnetic quantum number? The equations I am looking at contains both cosines and sines for many of the contractions. 

By change in sign, do you mean a factor of -1 is applied to the labelled spherical contractions?

**Comment by tovrstra** [comment]
The letter codes are defined in IOData here: 
https://github.com/theochem/iodata/blob/d1ab4a4b6be2952e9f572c869dc6cfd84b4b011b/iodata/basis.py#L32
and this was taken from https://en.wikipedia.org/wiki/Spectroscopic_notation#Atomic_and_molecular_orbitals
(or references therein).

I think only sine and cosine notation is unambiguous when you look at the equations. The distinction between negative and positive magnetic quantum number is mainly useful for complex spherical harmonics. As soon as you take linear combinations of these to form real functions, the meaning of the sign of the magnetic quantum number is lost. Please take a look at the equations here: https://en.wikipedia.org/wiki/Solid_harmonics#Real_form. C and S are common in case of the real functions.

Your interpretation of the minus sign is correct. This is needed because not every QC code is using the same definitions of the real solid harmonics.

**Comment by kimt33** [comment]
I will assume that C -> S_{l,m} and S -> S_{l, -m} using Helgaker's notation (6.4.2).

**Comment by kimt33** [comment]
Also, in MolecularBasis, doesn't the first element of the key (of conventions) corresponds to the angular momentum? Is there a case where the angular momentum char does not match up with the numerical angular momentum?

**Comment by kimt33** [comment]
If different QC code uses different definitions of real solid harmonics (different by a factor of -1), then which is considered to be -1?

**Comment by PaulWAyers** [comment]
For the letter codes, J is omitted because of confusion with the total angular momentum. I'm surprised that they don't also omit "M" but probably M doesn't show up frequently enough (and has a subscript L/J anyway).

**Comment by tovrstra** [comment]
Good, I assume Helgaker's convention is also the most wide spread in the QC world.

We could drop the first character for the angular momentum. Good point. It is there for historical reasons that don't matter anymore.

Also the convention of which is `+` and which is `-` has grown historically. Essentially the sign convention from FCHK files was taken as positive, which seemed to match with most other formats. The equations for the real solid spherical harmonics matching these sign conventions are given here: http://theochem.github.io/horton/2.1.1/tech_ref_gaussian_basis.html#pure-or-harmonic-basis-functions

P.S. If it matters, IOData can convert between different conventions, so you can use fixed conventions in gbasis if that makes things easier.

**Comment by tovrstra** [comment]
@kimt33 Is there still anything left that causes confusion? If not I'll take care of fixing the docstring soon.

**Comment by tovrstra** [comment]
I'm going to convert this issue in a few more specific tasks. If I overlook something, please let me know.

**Comment by tovrstra** [comment]
The tasks have been split up over issues #130, #131 and #132. I'm closing this one.
