### ISSUE TITLE
Drop character from basis ordering conventions for spherical shells.

### ISSUE THREAD

**Issue by tovrstra** [theochem/iodata#130]
This refers to the following convention:

https://github.com/theochem/iodata/blob/66c0553b3b18331a5b2279b1888c86607b377c64/iodata/basis.py#L152-L162

The convention for the pure functions can be simplified to

```python
(2, 'p'): ['c2', 'c1', 'c0', '-s1', '-s2'],
```

**Comment by tovrstra** [comment]
A particular benefit is that the conventions are not limited to or affected by letter conventions for angular momenta.

**Comment by tovrstra** [comment]
This was originally brought up in #121.

**Comment by tovrstra** [comment]
The minus signs should be removed from this example.

**Comment by tovrstra** [comment]
This docstring should refer to the documentation to be written in issue #131.

**Comment by FarnazH** [comment]
@tovrstra, this has been done, right?

**Comment by tovrstra** [comment]
@FarnazH Indeed. This was fixed in #133. I forgot to close this one.
