### ISSUE TITLE
Deploy fails

### ISSUE THREAD

**Issue by matt-chan** [theochem/iodata#14]
@tovrstra have you seen this error before? 

Current tag is: 0.1.1
/home/travis/.rvm/gems/ruby-2.2.7/gems/octokit-4.6.2/lib/octokit/client/releases.rb:86:in `initialize': No such file or directory @ rb_sysopen - dist/iodata-0.1.1.tar.gz (Errno::ENOENT)

It only happens on py27 for some weird reason

**Comment by tovrstra** [comment]
No, I would guess the source release is not created. Can you paste the link to the travis build?

**Comment by matt-chan** [comment]
Sure!

https://travis-ci.org/theochem/iodata/jobs/274671077

**Comment by tovrstra** [comment]
@matt-chan I guess this is solved, seeing 0.1.2 being released. The problem was that you pushed two tags (0.1.0 and 0.1.1) on the same commit. Part of the build script picks up one and another part picks up the other tag. I'm not sure when on gets priority over the other.
