### ISSUE TITLE
Making Title Section of Extended XYZ file format Parsable

### ISSUE THREAD

**Issue by FarnazH** [theochem/iodata#151]
The extended XYZ format allows extra columns to be added to the basic XYZ format to store additional atomic properties. `IOData` gives the user the option to specify the existing columns in a XYZ file through `atom_columns` of load/dump functionality.

I recently learned that sometimes the title section of an XYZ file is "standardized" to include cell lattice and other per-frame parameters, and hence be parseable. I have also seen machine-learning community storing energy and other global properties in the title section too. In this regard, I was wondering whether we would want to make the title section parsable or just keep storing the title as a string in `IOData.title`?

**Comment by PaulWAyers** [comment]
I think this is an interesting addition. We already have the fields for the cell-vecs and the frames work well in the _many functionality.

**Comment by evohringer** [comment]
I completely agree with @PaulWAyers. We are thinking to also support the cell lattice from pdb formats since this is important information for condensed phases.

I also like the idea of supporting additional informaciont of the title. Although I do not know how to implement it as an option when reading.

**Comment by tovrstra** [comment]
Indeed a good idea. I believe the conventions for the title line were introduced in the ASE project. I'm not sure if there is any other definition than just the source code: [extxyz.py](https://gitlab.com/ase/ase/-/blob/master/ase/io/extxyz.py) This is not to be confused with the [extended xyz format from openbabel](https://open-babel.readthedocs.io/en/latest/FileFormats/Extended_XYZ_cartesian_coordinates_format.html).

**Comment by tovrstra** [comment]
@mcoolsce has code for parsing the title of an extended XYZ and reading the data afterwards. He'd be happy to make a PR for this.

**Comment by PaulWAyers** [comment]
That would be great. Thanks @mcoolsce

**Comment by tovrstra** [comment]
This was implemented in #186.
