### ISSUE TITLE
Specify `runtype` vs. `run_type` and determine valid values

### ISSUE THREAD

**Issue by wilhadams** [theochem/iodata#162]
In #41 the attribute name storing the calculation type is given as `runtype`. Currently it is implemented as `run_type` in the fchk format parser and the `IOData` class. It would likely be easier for @tovrstra to edit this in the master list on #41 than to change the API now (I don't prefer one name over the other too strongly). 

In the fchk parser, the [current possible values](https://github.com/theochem/iodata/blob/master/iodata/formats/fchk.py#L115) for `run_type` are `'energy'`, `'opt'`, `'scan'`, and `'freq'`; in the `IOData` class docs, the [values given as examples](https://github.com/theochem/iodata/blob/master/iodata/iodata.py#L171) are `'energy'`, `'energy_force'`, `'opt'`, and `'freq'`. Should we be trying to make an exhaustive list of the possible `run_type` values now, or add them as they come? Regardless, the possible values should be documented (likely in the class docs), so that we're not ending up with redundant options.

This issue is important for generating input files (#43) and dumping input files to QCSchema or any other format (#39).

**Comment by tovrstra** [comment]
I've updated #41 to have `run_type` instead of `runtype`. I don't have any strong preference either.

Would it be sufficient to update the documentation along the following lines?

```
    run_type
        The type of calculation that lead to the results stored in IOData, which must be
        one of the following: 'energy', 'energy_force', 'opt', 'scan', 'freq' or None.
```

We can always extend this list to support more run types.

**Comment by wilhadams** [comment]
Sorry for the delay. Yes, that is great, thanks!

**Comment by wilhadams** [comment]
Preemptively closed this, I'll let @tovrstra 's PR close it instead
