### ISSUE TITLE
Error when trying to load Molden files with cartesian basis functions generated by last PSI4 version

### ISSUE THREAD

**Issue by leila-pujal** [theochem/iodata#163]
I generated some Molden files with new stable release version of PSI4 1.3.2 that can’t be load by IOData. Specifically, I got the problem when I try to load Molden files that use cartesian basis functions. Error arises in line 77 for molden.py in load_one function:

```
  File "/home/leila/iodata/iodata/formats/molden.py", line 77, in load_one
    _fix_molden_from_buggy_codes(result, lit)
  File "/home/leila/iodata/iodata/formats/molden.py", line 566, in _fix_molden_from_buggy_codes
    lit.error('Could not correct the data read from {}. The molden or mkl file '
  File "/home/leila/iodata/iodata/utils.py", line 92, in error
    raise FileFormatError("{}:{} {}".format(self.filename, self.lineno, msg))
iodata.utils.FileFormatError: nh3_psi4_cart_augccpvdz.molden:2998 Could not correct the data read from {}. The molden or mkl file you are trying to load contains errors. Please make an issue here: https://github.com/theochem/iodata/issues, and attach a this file. Please provide one or more small files causing this error.
```

I attached a compressed file with some example files: there are Molden files for h2o and nh3 systems, one file generated with spherical basis functions, and another generated with the same basis set but using cartesian. I am able to load the one generated using spherical but not for cartesian for both systems. I also attached PSI4 inputs/outputs I used for both systems.  
[molden_psi4.zip](https://github.com/theochem/iodata/files/4932795/molden_psi4.zip)

**Comment by tovrstra** [comment]
Thanks I'll take a look soon. (I've slightly reformatted your initial post for readability.) This is probably related to ordering of Cartesian functions. It may be a bug in PSI4 but we should add a solution in IOData first.

**Comment by tovrstra** [comment]
This is a problem in PSI4. I've reported the issue here: psi4/psi4#1973.
