### ISSUE TITLE
Move to pkg_resources

### ISSUE THREAD

**Issue by matt-chan** [theochem/iodata#17]
Forgot to update iodata to pkg_resources. Still using __file__. 

Maybe even jump to importlib.resources directly.

**Comment by tovrstra** [comment]
Yes, `importlib` is good.

**Comment by tczorro** [comment]
1. keep get_fn, but replace the implementation with importlib
2. complete remove get_fn and use importlib to handle "data", but return a “str” path
3. change the IO in iodata so it can handle Path file as well.

**Comment by tovrstra** [comment]
I'm not sure what you mean by `Path file`? I think option 2 is the best one, relatively little work and getting rid of redundant code.

**Comment by tovrstra** [comment]
Oh I see. Converting it to string in the test (as in Chemtools) seems is fine for now. Future changes will make IOData compatible with Path objects (#6), so no need to worry about it now.

**Comment by tczorro** [comment]
I just reverted all the necessary update I made, only keeping the parts related to this issue.
