### ISSUE TITLE
Document required `attrs` package

### ISSUE THREAD

**Issue by wilhadams** [theochem/iodata#201]
The `attrs` package is requred for IOData, but there's no mention of it anywhere in the README nor the developer documentation. This is also important because there's also an `attr` package, with similar functionality, and the import statement for the `attrs` package is `import attr`, which is confusing. I think putting a brief overview of how `attrs` works within IOData into the developer docs would make it easier for new developers to contribute.

**Comment by tovrstra** [comment]
@wilhadams Thanks for the suggestion. I'll take care of this in #157. This PR converts one namedtuple to an attr class. We should do also the remaining ones, and add a few words of explanation to how it is used. We mainly use it for attribute validation and avoiding lengthy classes.
