### ISSUE TITLE
`format/json` error

### ISSUE THREAD

**Issue by tczorro** [theochem/iodata#225]
No module named 'iodata.version' when import iodata.
This problem can be fixed by commenting out `from ..version import __version__`

**Comment by tovrstra** [comment]
The file `version.py` is generated by running `rob write-version`, which derives it from the git tag.

**Comment by tovrstra** [comment]
P.S. This is what it generates for me on the master branch, in case you want to check:

```python
"""Autogenerated version information file.

Manual changes to this file will be overwritten.

The output of git describe was: ``1.0.0a1-254-ga7000f8``

The derived version is: ``1.0.0a1.post254``
"""
__version__ = '1.0.0a1.post254'
DEV_CLASSIFIER = 'Development Status :: 2 - Pre-Alpha'
```

More info can be found in `CONTRIBUTING.md`
