### ISSUE TITLE
Add robust features to Gaussian input files

### ISSUE THREAD

**Issue by BradenDKelly** [theochem/iodata#234]
- [feature request] 

The current `write_input()` for Gaussian works well for typical jobs that require only having a theory, basis and simple task i.e., opt, energy etc. But a more complicated directive does not seem possible?

For instance if I want to make the following input file, is it possible?
```
%NProcShared=4
%mem=16GB
%chk=B3LYP_def2-qzvp_Be_13_O_14
#p nosymmetry B3LYP def2qzvp scf=(maxcycle=900,verytightlineq,xqc) integral=(grid=ultrafinegrid) pop=(cm5, hlygat, mbs, npa, esp) 

much fun, great quantum

-2 1
O 0.0 0.0 0.0
O 3.7 0.0 0.0
... (other atoms etc)
```
I mention this because I want to make these types of inputs. If this seems like a good thing to add, I can work on it and submit a PR.

Would a simple solution be to add a 'directive' attribute to 'IOData'?
`iodata.directive = "scf=(maxcycle=900,verytightlineq,xqc) integral=(grid=ultrafinegrid) pop=(cm5, hlygat, mbs, npa, esp) "`

similarly for specifying
```
%NProcShared=4
%mem=16GB
%chk=B3LYP_def2-qzvp_Be_13_O_14
```
these could be attributes or inside the extra dict?

**Comment by wilhadams** [comment]
One way you could do this with the input writer in the current state is to provide your own template through the `template` arg, instead of using [the default Gaussian template](https://github.com/theochem/iodata/blob/master/iodata/inputs/gaussian.py#L35).

**Comment by PaulWAyers** [comment]
I'm curious what @tovrstra  and @FarnazH  think, but I think beyond "simple" Gaussian input files we may be making much more work than we want.....the `template` idea Wil mentions seems stronger, and really is what we would expect to *have* to do when we are doing large databases of calculations that need fairly specific inputs.

**Comment by tovrstra** [comment]
Indeed, the reason for having the (optional) `template` argument is to provide flexibility for this scenario. It works well as long as the extra bits in the template do not depend on the properties of the molecule. Anything beyond that would require some extra infrastructure, either inside IOData, or by the code that provides the template.

**Comment by BradenDKelly** [comment]
The template works, so that solves my problem. I do have a question/suggestion... the template is an external file, which is fine, but it wouldn't be much more work to make it so that the template could be passed as a string.

currently in the [api.py](https://github.com/theochem/iodata/blob/95af9914463326e74772d64c0dacd92658f98321/iodata/api.py#L229) we pass the name of the physical file and then in `write_input(...)`
```
 input_module = _select_input_module(fmt)
 # load template as a string
 if template is not None:
      with open(template, 'r') as t:
           template = t.read()
 with open(filename, 'w') as f:
     input_module.write_input(f, iodata, template=template, **kwargs)
```
However in my own script which uses `iodata`, I think I would rather just define a string such as 

```
import numpy as np
from iodata import load_one, write_input

bradens_template = """\
%NProcShared=4
%mem=16GB
%chk=B3LYP_def2-qzvp_Be_13_O_14
#n ${lot}/${obasis_name} scf=(maxcycle=900,verytightlineq,xqc) integral=(grid=ultrafinegrid) pop=(cm5, hlygat, mbs, npa, esp) 

${title}

${charge} ${spinmult}
${geometry}

"""

mol = load_one('water.pdb')
mol.lot = "B3LYP"
mol.obasis_name = "cc-pVTZ"
write_input(mol, "water.com", template=bradens_template, fmt="gaussian")
```
With a string, it is easy for me to modify, for instance, the name of the checkpoint file. It would also be easy to change the checkpoint file name in the physical template, but seems unnecessary.

I think a simple change would be to add to the `if` statement a check so that [api.py](https://github.com/theochem/iodata/blob/95af9914463326e74772d64c0dacd92658f98321/iodata/api.py#L229) now has (for write_input)
```
def write_input(iodata: IOData, filename: str, fmt: str, template: str = None, template_is_str: bool = False, **kwargs):
    # *** ommited stuff for brevity... ***
    input_module = _select_input_module(fmt)
    # load template as a string
    if template is not None and not template_is_str:    # modified if statement
        with open(template, 'r') as t:
            template = t.read()
       with open(filename, 'w') as f:
           input_module.write_input(f, iodata, template=template, **kwargs)
```
the additional input of `template_is_str` is necessary since both a template name, or string are `type str`, otherwise I would just use a type check. A more sophisticated check of whether the template string is a filename could be implemented, but, this seems simpler.

Would this be worth implementing? I can always just do this in my own version, but it isn't api breaking and others may prefer just defining a simple template as a string rather than hauling a physical template around?

**Comment by wilhadams** [comment]
I agree with Braden, it would be great to accept a string for the template argument. Perhaps we could make `template` correspond to a template string input, and add another argument `template_file` for cases when reading from file are desired. 

@tovrstra - what do you think? I'd be happy to implement whatever version of accepting strings, and could add a small section to the docs detailing the different ways of using the template, both for allowing the default template and passing a string or filename.

It would also probably be good to add the default template for each input type to the "Supported Input Formats" docs page, so that it's available without digging around too much.

**Comment by tovrstra** [comment]
I also agree with Braden. It is quite convenient to define and prepare the input template as a Python string. I would suggest to drop the possibility to pass in a filename as argument and always assume it is the template string itself. If someone wants to read it from a file, the extra effort is trivial:

```python
write_input(mol, "water.com", template=bradens_template, fmt="gaussian")
```

or 

```python
write_input(mol, "water.com", template=open("bradens_template.com").read(), fmt="gaussian")
```

We're not at IOData version 1.0, so changing API is still ok.
