### ISSUE TITLE
Use `.format` method instead of `template` module in `write_input`

### ISSUE THREAD

**Issue by tovrstra** [theochem/iodata#241]
The `.format` method is more powerful than the `template` module and would make it easier to add more features to the input writer without adding much more code. For example, the following is something only the `.format` method can do:

```python
print("access element from dict: {d[foo]}".format(d={"foo": "bar"}))
```

**Comment by wilhadams** [comment]
@tovrstra Do you want me to take care of this?

**Comment by tovrstra** [comment]
That would be great. Just replacing `template` by `.format` should not cause trouble but it is will take quite a bit of changes in many places.
