### ISSUE TITLE
Update installation instructions

### ISSUE THREAD

**Issue by tovrstra** [theochem/iodata#29]
The terminology in the install docs is not very clear. A few things to improve:

- "Installation (from source)" should become "Build conda package (from source)". It should also be specified which source: a source release tar file or github clone, or do both work? One line could be added to explain how to install a locally built package. It is worth explaining that this is the safe alternative to a more conventional from-source installation.

- "Installation (by hand)" should become "Installation (from source)" and should be a little more elaborate. For the version requirements, we can refer to to the conda build script, rather than reproducing it here. We should also point out the difference between a source release and a git clone. (version.py) We should explicitly mention that this option is something we do not support in case it goes wrong. An installation from source can go wrong in many ways. This is only suitable for devs who know how to fix things when they break.

**Comment by tovrstra** [comment]
P.S. We should probably not try to support anything else than installing the conda binary package.

**Comment by matt-chan** [comment]
Yeah, for regular users 100%. 

I'm not sure what options to provide for new developers though. It takes a lot of time to build conda packages each time you want to test something.

**Comment by tovrstra** [comment]
I see. Let me try to get some hands-on experience with this, so I can make some more useful suggestions.

**Comment by tovrstra** [comment]
Was already fixed here: https://github.com/theochem/iodata/commit/74302b169bdeae36d262ec6b853ff6f63e78c36f

More docu updates are made in #105
