### ISSUE TITLE
Can I trust IOData for handling molden files generated from PySCF

### ISSUE THREAD

**Issue by yingxingcheng** [theochem/iodata#293]
Does anybody know if the IOData supports the 'molden' files generated from the PySCF program?

**Comment by PaulWAyers** [comment]
I'm not sure. `*.molden` files are a bit of a strange beast, but it could be tested. @tovrstra is the person who spearheaded the (rather good) ability of `IOData` to handle a wide variety of `*.molden` files, so I'd ask him. He's right next door, after all....

**Comment by tovrstra** [comment]
That depends on PySCF. It would not be the first program to generate broken Molden files. Whenever you load a Molden file with IOData, the normalization of the orbitals is tested to make sure the data are somewhat sensible. It is not a perfect test, but it prevents most of the common issues.
