### ISSUE TITLE
Python 3.9 Numpy 1.20 Depreciation: np.int, np.float

### ISSUE THREAD

**Issue by Ali-Tehrani** [theochem/iodata#307]
In [Numpy 1.20.0](https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated), np.int and np.float are depreciated and should be replaced with int and float.  From looking at the website above, this is a very easy fix to do and good for a beginner for learning CI/Git/Github, if I have time later in the week I could do it as well.

Where it occured, the following is an error I get from reading a ".wfx" file:
```python
  File "/home/tehrana/py39/lib/python3.9/site-packages/iodata/api.py", line 142, in load_one
    iodata = IOData(**format_module.load_one(lit, **kwargs))
  File "/home/tehrana/py39/lib/python3.9/site-packages/iodata/formats/wfx.py", line 218, in load_one
    data = load_data_wfx(lit)
  File "/home/tehrana/py39/lib/python3.9/site-packages/iodata/formats/wfx.py", line 134, in load_data_wfx
    result[lbs_aint[key]] = np.fromstring(" ".join(value), dtype=np.int, sep=" ")
  File "/home/tehrana/py39/lib/python3.9/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

**Comment by Ali-Tehrani** [comment]
That would be great! Thank you, @LudoRNLT and @D-TheProgrammer.  Let me know if you have any questions/concerns.

**Comment by PaulWAyers** [comment]
Thanks! We are happy to have your help. I have added you both to the QC-Devs GitHub organization.

**Comment by Ali-Tehrani** [comment]
Oh wow, thanks, yes that's the solution to the problem! I was using an old version of IOData. How silly of me. 

If you're still interested for your assignment, there is another issue that has a quick, easy solution to it that will involve some coding. Thank you for looking into this.

**Comment by Ali-Tehrani** [comment]
Okay thank you!
