### ISSUE TITLE
Fix Factorial2

### ISSUE THREAD

**Issue by Ali-Tehrani** [theochem/iodata#308]
The most recent merged [pull-request](https://github.com/theochem/iodata/pull/301) causes 165 tests to fail in Github [Actions](https://github.com/theochem/iodata/actions/runs/7161627372/job/19497490702#step:6:9878) for various python systems.  The following error is obtained for the vast majority of them:
```python
     def factorial2(n, exact=False):
        """Wrap scipy.special.factorial2 to return 1.0 when the input is -1.
    
        This is a temporary workaround while we wait for Scipy's update.
        To learn more, see https://github.com/scipy/scipy/issues/18409.
    
        Parameters
        ----------
        n : int or np.ndarray
            Values to calculate n!! for. If n={0, -1}, the return value is 1.
            For n < -1, the return value is 0.
        """
        # Scipy  1.11.x returns an integer when n is an integer, but 1.10.x returns an array,
        # so np.array(n) is passed to make sure the output is always an array.
        out = scipy.special.factorial2(np.array(n), exact=exact)
>       out[out <= 0] = 1.0
E       TypeError: 'int' object does not support item assignment
```

Further the following [line](https://github.com/theochem/iodata/blame/6b9c6e0e94a0425593217954f3913f4545a5605d/iodata/overlap.py#L240) does not match [scipy.factorial2](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.factorial2.html) API.  Looking at the earlier release of this package, we want `exact=True` in scipy.factorial2.  When setting `exact=True`, then scipy.factorial2 only accepts integers, and so we will need to run it over each individual element of the array.

The solution would be too in `factorial2` function:
1. Keep `out = scipy.special.factorial2(np.array(n), exact=exact)` when exact=False
2. When exact=True, and 
   i. Add if n is not `int`, then convert it to array `n = np.array([n])`) 
   ii.  compute `scipy.special.factorial2(x, exact)` on each individual element `x` of the array `n`.
   
Thank you to @LudoRNLT and @D-TheProgrammer, if you got the time to look into this.

**Comment by PaulWAyers** [comment]
@Ali-Tehrani is this also going to be an issue in [`GBasis`](https://github.com/theochem/gbasis/blob/9f6afe7ffc56b9a4e7f8a4a74d0fa5f01197ebca/gbasis/utils.py#L7)?

**Comment by Ali-Tehrani** [comment]
I doubt it will be a problem at all, since GBasis will only go up to like 7-11!!   and the performance advantages are much greater

**Comment by Ali-Tehrani** [comment]
No worries, if you want to run in the format you specified, you should be removing the .py and be in the `iodata` directory:
```
python3 -m iodata.test.common
```

However, I would recommend to use `pytest` instead to see that the tests pass like so:
```
pytest -v -s ./iodata/test/*.py   # -s means it prints while it runs
```
Adding `-s` makes it easier to debug and see what's being printed. Good luck, let me know if you have any other questions!
