### ISSUE TITLE
Use np.testing when appropriate in unit tests

### ISSUE THREAD

**Issue by tovrstra** [theochem/iodata#32]
When comparing floating point results, `numpy.testing` offers nicer functions than a bare assert. Many of the unit tests should be converted to use `numpy.testing` instead.

**Comment by tovrstra** [comment]
The Numpy docs recommend using `assert_allclose` instead of `assert_almost_equal`. See https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.testing.assert_almost_equal.html

**Comment by PaulWAyers** [comment]
Or maybe use the Python (not numpy) intrinsic:
math.isclose(a, b, *, rel_tol=1e-09, abs_tol=0.0)

Probably clunkier without the "assert" built in....

**Comment by FarnazH** [comment]
I believe we are switching to `pytest`, so we should use that.

**Comment by fwmeng88** [comment]
The `numpy.testing.assert_allclose` is asymmetric, which means that `a=b` might result b not equal a. For example (taken from https://stackoverflow.com/questions/48156460/isclose-function-in-numpy-is-different-from-math)
```
a = 0.142253
b = 0.142219
rel_tol = 1e-4
abs_tol = 1.9776e-05
# test failed
numpy.testing.assert_allclose(actual=a, desired=b, rtol=rel_tol, atol=abs_tol)
# test passed
np.testing.assert_allclose(actual=b, desired=a, rtol=rel_tol, atol=abs_tol)
```
But for `math.isclose(a, b, *, rel_tol=1e-09, abs_tol=0.0)` , it seems only support scaler instead of numpy array.
```
a = np.linspace(0., 1., 100).reshape(10, 10)
b = np.arcsin(np.sin(a))
# this will raise an TypeError
math.isclose(a, b, rel_tol=1e-09, abs_tol=0.0)
```
Once an agreement is reached, I can start working on this.

**Comment by PaulWAyers** [comment]
It sounds to me like you should use numpy.testing.assert_allclose

The nuance of directionality is unlikely to be important; the example is a rather evil one. To the extent that you can identify one value which is "reference" and one which is "approximate" you should make sure the "desired" is the reference.
