### ISSUE TITLE
dump functions for QM input files

### ISSUE THREAD

**Issue by tovrstra** [theochem/iodata#39]
We could use the input spec based on MOLSSI schema

**Comment by FarnazH** [comment]
@tovrstra, how is this different from issue #43?

**Comment by tovrstra** [comment]
#43 does not refer to the input spec from MOLSSI but I'm not sure how relevant this is?

**Comment by wilhadams** [comment]
@FarnazH I'll try to document the qcschema_input schema so that it's relatively simple to dump QM input file info to JSON

**Comment by PaulWAyers** [comment]
@wilhadams can you make sure that every field that exists in the IOData object exists at least as an optional field in JSON? That way we can use the JSON for long-term storage (though a pickle of the IOData object can still be useful for short-term storage). 

(Hat-tip Toon)

**Comment by tovrstra** [comment]
closed in favour of #43.
