### ISSUE TITLE
Update unit conversion constants

### ISSUE THREAD

**Issue by tovrstra** [theochem/iodata#4]
We should update our units to be complete and up-to-date with the latest NIST values: https://physics.nist.gov/cgi-bin/cuu/Category?view=html&Non-SI+units.x=87&Non-SI+units.y=16

It could also be interesting to study how others deal with unit conversion. However, most of these seem to be overkill, compared to the approach in iodata:
* https://github.com/hgrecco/pint
* https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/unit/unit_definitions.py

**Comment by tovrstra** [comment]
Also, iodata only uses a small part of the units module from HORTON. We should probably have a simple units module (separate repo) to be used in glue code.

**Comment by FarnazH** [comment]
Consider using `scipy.constants`.

**Comment by tovrstra** [comment]
Yes, `scipy.constants` is good.
