### ISSUE TITLE
Provide input to MolSSI/QC_JSON_Schema, such that it works well for us

### ISSUE THREAD

**Issue by tovrstra** [theochem/iodata#5]
@matt-chan Ideally, our package should be able to write out a JSON file that is compatible with [MolSSI/QC_JSON_Schema](https://github.com/MolSSI/QC_JSON_Schema), with as much as possible data that we typically get from various file formats. We should either open issues are make changes to iodata.

**Comment by FarnazH** [comment]
This turned out to be a major ordeal. @wilhadams is working on this; please check PR #144.
