### ISSUE TITLE
Add API to load trajectories or databases, one molecule at a time

### ISSUE THREAD

**Issue by tovrstra** [theochem/iodata#7]
Typical examples are XYZ files (e.g. for MD trajectories) or SDF files (databases of molecules). For both formats, it is desirable to have an iterator over the repeated items (usually molecules), without reading the entire file at once into memory.

**Comment by tovrstra** [comment]
Issue #26 is essential the same as this one.

**Comment by tovrstra** [comment]
Another use case is Reaction Trajectory & IRC (Intrinsic Reaction Coordinate) See https://github.com/stvogt/kudi and http://gaussian.com/irc/

**Comment by FarnazH** [comment]
Covering trajectory stored in:
- `xyz` file
- `sdf` file
- `log` file

API: `load_trajectory(filename)` returning a list of `IOData`. We need to change the `IOData.load/dump` methods to get a `file_object` and read/dump one chunk.

**Comment by tovrstra** [comment]
Here is a list of steps we need to take to support trajectories:

- [ ] Change `IOData.from_file` to `load_one`. Change `IOData.tp_file` to `dump_one`.
- [ ] Change all load functions to take a file object as argument, instead of a file. They should also only load data until they have found enough to make one IOData object. When hitting the end of a file, it should raise a `StopIteration`. See https://docs.python.org/3.7/library/exceptions.html#StopIteration. This also means `load_one` should open the file object.
- [ ] Similar to previous but for `dump_one`
- [ ] Write `load_many` and `dump_many` functions.
