### ISSUE TITLE
Add convenience properties to `MolecularOrbitals`: `coeffs_a`, ...

### ISSUE THREAD

**Issue by tovrstra** [theochem/iodata#77]
It may be useful to make `coeffs_a` and `coeffs_b` properties of the MolecularOrbitals class. Similarly, one could make `energies_a`, `energies_b`, `occs_a` and `occs_b`.

All of these should return None on the generalized case. In case of restricted, `coeffs_b` and `energies_b` should be None, and elements of `occs_a` and `occs_b` should be at most one

_Originally posted by @tovrstra in https://github.com/theochem/iodata/pull/76_

**Comment by FarnazH** [comment]
@tovrstra This seems like going back to having separate arrays for alpha and beta components (when we had `orb_alpha`, `orb_alpha_coeffs`, `orb_alpha_energies`, `orb_alpha_occs` and corresponding `beta` counterparts); just that now they are sitting all in `MolecularOrbital` class. Is that true?

I understand that this seems easier to understand/retrieve, but what I don't like is constantly checking whether `beta` coefficients exist. Taking 1DM computation as an example, currently, we can write (disregarding of being `restricted` or `unrestricted`):

```
coeffs, occs = iodata.mo.coeffs, iodata.mo.occs
dm = np.dot(coeffs * occs, coeffs.T)
```

Separating `alpha` and `beta` components, as we previsouly had, makes 1DM computation lengthier:

```
coeffs, occs = iodata.orb_alpha_coeffs, iodata.orb_alpha_occs
dm = np.dot(coeffs * occs, coeffs.T)
if hasattr(iodata, 'orb_beta_coeffs'):
    coeffs, occs = iodata.orb_beta_coeffs, iodata.orb_beta_occs
    dm += np.dot(coeffs * occs, coeffs.T)
else:
    dm *= 2
```

I also understand that `IOData` isn't supposed to care much about computations, but instead store the data clearly, so I am fine either way. It is something that can be resolved in wrappers.

**Comment by tovrstra** [comment]
@FarnazH Sorry for the confusion, my original post was not very clear. This would only be an extension with some extra properties (not attributes). We should keep the current array attributes because they are convenient as you mention. I would only suggest to add properties for convenience, e.g.

```python
@property
def coeffs_a(self):
    return self.coeffs[:, :self.norb_a]
```

(Or `acoeffs`, whichever works best.) The purpose of such properties is to improve the readability of code using only alpha or beta orbital information, but not to change the way the data is stored.
